border_width = 2
margin = [8, 8]

#Candy colors
default_border_color = "#bd93f9"
floating_border_color = "#bd93f9"
focused_border_color = "#ff79c6"

#Default ArcoLinux colors
#default_border_color = "#4c566a"
#floating_border_color = "#4c566a"
#focused_border_color = "#5e81ac"
